### ISSUE TITLE
Parallell processing

### ISSUE THREAD

**Issue by ivank** [chrisbenincasa/berglas-node#4]
Hey awesome library! 

Works quite well, however I substitute calls for me can take quite a while to resolve, if you have a a bunch of env variables to substitute.

It would be quite easy to 
 - go through all of the env variables to substitute and group them by bucket. 
 - download all the files from their buckets In parallel
 - decrypt the keys in parallel

Right now the substitute function is O(N) and for most use cases it should be more like O(1).

I'll be more than happy to do a PR, but it might be a substantial change and wanted to ask what you think about it first :)

What do you think?

**Comment by chrisbenincasa** [comment]
Great idea! I just merged your pull request - much appreciated! This should be available in version 1.0.3 now.
